//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelecaoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public long id { get; set; }
        public string nome { get; set; }
        public long fornecedor { get; set; }
        public int quantidade { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
    }
}
